site:
  title: Antora Docs
  start_page: main::getting-started.adoc
content:
  sources:
  - url: https://github.com/lee-carlon/Antora-test.git
    branches: [main]
    tags: ~
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true